server:
  context-path: /cmfz
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://127.0.0.1:3306/cmfz?characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.baizhi.entity